package com.alehyem.personalfinances;

public final class NamesConstants {
    public static final String AMOUNT = "AMOUNT";
    public static final String COMMAND_ATTRIBUTE = "COMMAND_ATTRIBUTE";
    public static final String COMMON_SERVLET_PATH = "/ControllerServlet";
    public static final String COUNTRIES_LIST = "COUNTRIES_LIST";
    public static final String CURRENT_PAGE = "CURRENT_PAGE";
    public static final String CURRENT_PRICE = "CURRENT_PRICE";
    public static final String CURRENT_USER = "CURRENT_USER";
    public static final String CURRENT_USER_BALANCE = "CURRENT_USER_BALANCE";
    public static final String CURRENT_USER_BALANCE_TRANSACTIONS = "CURRENT_USER_BALANCE_TRANSACTIONS";
    public static final String CURRENT_USER_ID = "CURRENT_USER_ID";
    public static final String CURRENT_USER_LOGIN = "CURRENT_USER_LOGIN";
    public static final String CURRENT_USER_ROLE = "CURRENT_USER_ROLE";
    public static final String CURRENT_USER_PASSWORD = "CURRENT_USER_PASSWORD";
    public static final String CURRENT_USER_EMAIL = "CURRENT_USER_EMAIL";
    public static final String CURRENT_USER_NAME = "CURRENT_USER_NAME";
    public static final String CURRENT_USER_SURNAME = "CURRENT_USER_SURNAME";
    public static final String CURRENT_USER_COUNTRY = "CURRENT_USER_COUNTRY";
    public static final String DATE = "DATE";
    public static final String DIVIDENDS = "DIVIDENDS";
    public static final String ERROR_ATTRIBUTE = "ERROR_ATTRIBUTE";
    public static final String EMPTY_STRING = "EMPTY_STRING";
    public static final String EXCHANGES_LIST = "EXCHANGES_LIST";
    public static final String INTERNAL_ERROR = "INTERNAL_ERROR";
    public static final String MAX_ITEMS_PER_PAGE = "MAX_ITEMS_PER_PAGE";
    public static final String LANG = "lang";
    public static final String PAGES_AMOUNT = "PAGES_AMOUNT";
    public static final String PARAMETERS_MAP = "PARAMETERS_MAP";
    public static final String PORTFOLIO = "PORTFOLIO";
    public static final String PORTFOLIO_ID = "PORTFOLIO_ID";
    public static final String PORTFOLIOS_LIST = "PORTFOLIOS_LIST";
    public static final String PORTFOLIO_NAME = "PORTFOLIO_NAME";
    public static final String PORTFOLIO_SECURITIES = "PORTFOLIO_SECURITIES";
    public static final String PORTFOLIO_TRANSACTIONS = "PORTFOLIO_TRANSACTIONS";
    public static final String PORTFOLIO_USER_ID = "PORTFOLIO_USER_ID";
    public static final String PRICE = "PRICE";
    public static final String REQUEST_METHOD = "REQUEST_METHOD";
    public static final String REQUEST_USER_PARAM_ROLE = "role";
    public static final String REQUEST_USER_PARAM_ID = "id";
    public static final String REQUEST_USER_PARAM_LOGIN = "login";
    public static final String REQUEST_USER_PARAM_PASSWORD = "password";
    public static final String REQUEST_USER_PARAM_REMEMBER_ME = "rememberMe";
    public static final String REQUEST_USER_PARAM_EMAIL = "email";
    public static final String REQUEST_USER_PARAM_NAME = "name";
    public static final String REQUEST_USER_PARAM_SURNAME = "surname";
    public static final String REQUEST_USER_PARAM_COUNTRY = "country";
    public static final String REQUEST_PORTFOLIO_PARAM_NAME = "name";
    public static final String REDIRECT_LINK = "REDIRECT_LINK";
    public static final String REQUEST_URI = "REQUEST_URI";
    public static final String SECURITIES_LIST = "SECURITIES_LIST";
    public static final String SECURITY = "SECURITY";
    public static final String SECURITY_DIVIDENDS = "SECURITY_DIVIDENDS";
    public static final String SECURITY_EXCHANGE = "SECURITY_EXCHANGE";
    public static final String SECURITY_NAME = "SECURITY_NAME";
    public static final String SECURITY_PRICE = "SECURITY_PRICE";
    public static final String SECURITY_SYMBOL = "SECURITY_SYMBOL";
    public static final String SECURITY_PRICES_LIST = "SECURITY_PRICES_LIST";
    public static final String SECURITY_STOP_TRADE_DATE = "SECURITY_STOP_TRADE_DATE";
    public static final String SECURITY_TRANSACTIONS = "SECURITY_TRANSACTIONS";
    public static final String SECURITY_TYPE = "SECURITY_TYPE";
    public static final String SECURITY_TYPES_LIST = "SECURITY_TYPES_LIST";
    public static final String SECURITY_YEAR_CHANGE = "SECURITY_YEAR_CHANGE";
    public static final String STATUS_CODE = "STATUS_CODE";
    public static final String TRANSACTION = "TRANSACTION";
    public static final String TRANSACTION_ID = "TRANSACTION_ID";
    public static final String TRANSACTION_PORTFOLIO_ID = "TRANSACTION_PORTFOLIO_ID";
    public static final String TRANSACTION_SECURITY_SYMBOL = "TRANSACTION_SECURITY_SYMBOL";
    public static final String TRANSACTIONS_BAN_STATUS = "TRANSACTIONS_BAN_STATUS";
    public static final String TRANSACTIONS_LIST = "TRANSACTIONS_LIST";
    public static final String TRANSACTION_TYPE = "TRANSACTION_TYPE";
    public static final String USERS_LIST = "USERS_LIST";
    public static final String USER = "USER";
    public static final String USER_BAN_STATUS = "USER_BAN_STATUS";
    public static final String USER_ID = "USER_ID";
    public static final String YEAR_CHANGE = "YEAR_CHANGE";

    private NamesConstants() {
        throw new UnsupportedOperationException();
    }
}
